const express = require('express');
const path = require('node:path');
const { Pool } = require('pg');
const app = express();
const port = Number(process.env.PORT || 3000);
const pool = new Pool({connectionString: process.env.DATABASE_URL || 'postgres://facts:facts@localhost:5432/facts'});
app.use(express.json({limit:'1mb'}));
app.use(express.static(path.join(__dirname,'public')));
const json = (v, fallback={}) => { if (v === undefined || v === null || v === '') return fallback; if (typeof v === 'object') return v; try { return JSON.parse(v); } catch { return fallback; } };
app.get('/api/health', async (_req,res) => { try { await pool.query('SELECT 1'); res.json({ok:true,version:'0.0.0-pre-alpha.1'}); } catch (e) { res.status(503).json({ok:false,error:e.message}); } });
app.get('/api/types', async (req,res) => { try { const p=req.query.kind?[req.query.kind]:[]; const r=await pool.query(`SELECT * FROM type_definitions ${p.length?'WHERE kind=$1':''} ORDER BY kind,name`,p); res.json(r.rows); } catch(e) { res.status(500).json({error:e.message}); } });
app.post('/api/types', async (req,res) => { const {kind,name,description='',schema={}}=req.body||{}; if(!['entity','relationship','view','presentation'].includes(kind)||!name?.trim()) return res.status(400).json({error:'kind and name are required'}); try { const r=await pool.query('INSERT INTO type_definitions (kind,name,description,schema) VALUES ($1,$2,$3,$4) RETURNING *',[kind,name.trim(),description,json(schema)]); res.status(201).json(r.rows[0]); } catch(e) { res.status(e.code==='23505'?409:500).json({error:e.message}); } });
app.get('/api/entities', async (_req,res) => { try { const r=await pool.query('SELECT e.*,t.name AS type_name FROM entity_records e JOIN type_definitions t ON t.id=e.type_id ORDER BY e.created_at DESC'); res.json(r.rows); } catch(e) { res.status(500).json({error:e.message}); } });
app.post('/api/entities', async (req,res) => { const {typeId,name,data={}}=req.body||{}; if(!typeId||!name?.trim()) return res.status(400).json({error:'typeId and name are required'}); try { const r=await pool.query('INSERT INTO entity_records (type_id,name,data) VALUES ($1,$2,$3) RETURNING *',[typeId,name.trim(),json(data)]); res.status(201).json(r.rows[0]); } catch(e) { res.status(500).json({error:e.message}); } });
app.get('/api/relationships', async (_req,res) => { try { const r=await pool.query('SELECT r.*,t.name AS type_name,f.name AS from_name,to_entity.name AS to_name FROM relationship_records r JOIN type_definitions t ON t.id=r.type_id JOIN entity_records f ON f.id=r.from_entity_id JOIN entity_records to_entity ON to_entity.id=r.to_entity_id ORDER BY r.created_at DESC'); res.json(r.rows); } catch(e) { res.status(500).json({error:e.message}); } });
app.post('/api/relationships', async (req,res) => { const {typeId,fromEntityId,toEntityId,data={}}=req.body||{}; if(!typeId||!fromEntityId||!toEntityId) return res.status(400).json({error:'typeId, fromEntityId and toEntityId are required'}); try { const r=await pool.query('INSERT INTO relationship_records (type_id,from_entity_id,to_entity_id,data) VALUES ($1,$2,$3,$4) RETURNING *',[typeId,fromEntityId,toEntityId,json(data)]); res.status(201).json(r.rows[0]); } catch(e) { res.status(500).json({error:e.message}); } });
app.get('*', (_req,res) => res.sendFile(path.join(__dirname,'public','index.html')));
if(require.main===module) app.listen(port,()=>console.log(`FACTS listening on http://localhost:${port}`));
module.exports={app,pool};
